#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e





printf "⏳ Provisioning IoT devices "


#
# Create a service groups for all UltraLight IoT devices
#

curl -s -o /dev/null -X POST \
  'http://iot-agent:4041/iot/services' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "services": [
   {
     "apikey":      "321701236",
     "cbroker":     "http://orion:1026",
     "entity_type": "TemperatureSensor",
     "resource":    "/iot/d",
     "protocol":    "PDI-IoTA-UltraLight",
     "transport":   "HTTP",
     "timezone":    "Europe/Berlin",
     "attributes": [
       { "object_id": "t", "name":"temperature", "type": "Integer",
         "metadata": {"unitCode": {"type": "Property","value": "CEL"}}
       }
      ],
      "static_attributes": [
        {"name": "description", "type":"Property", "value": "Temperature Sensor"},
        {"name": "category", "type":"Property", "value": ["sensor"]},
        {"name": "controlledProperty", "type": "Property", "value": "temperature"},
        {"name": "supportedProtocol", "type": "Property", "value": ["ul20"]}
      ]
   },
   {
     "apikey":      "548027571",
     "cbroker":     "http://orion:1026",
     "entity_type": "SoilSensor",
     "resource":    "/iot/d",
     "protocol":    "PDI-IoTA-UltraLight",
     "transport":   "HTTP",
     "timezone":    "Europe/Berlin",
     "attributes": [
       { "object_id": "h", "name":"humidity", "type": "Integer",
         "metadata": {"unitCode": {"type": "Property","value": "P1"}}
       }
      ],
      "static_attributes": [
        {"name": "description", "type":"Property", "value": "Soil Humdity Sensor"},
        {"name": "category", "type":"Property", "value": ["sensor"]},
        {"name": "controlledProperty", "type": "Property", "value": "humidity"},
        {"name": "supportedProtocol", "type": "Property", "value": ["ul20"]}
      ]
   },
   {
     "apikey":      "854782081",
     "cbroker":     "http://orion:1026",
     "entity_type": "FillingSensor",
     "resource":    "/iot/d",
     "protocol":    "PDI-IoTA-UltraLight",
     "transport":   "HTTP",
     "timezone":    "Europe/Berlin",
     "attributes": [
       { "object_id": "f", "name":"filling", "type": "Number",
         "metadata": {"unitCode": {"type": "Property","value": "C62"}}
       }
      ],
      "commands": [
        {"name": "add", "type": "command"},
        {"name": "remove", "type": "command"}
      ],
      "static_attributes": [
        {"name": "supportedProtocol", "type": "Property", "value": ["ul20"]},
        {"name": "description", "type":"Property", "value": "Barn filling Sensor"},
        {"name": "category", "type":"Property", "value": ["actuator", "sensor"]},
        {"name": "controlledProperty", "type": "Property", "value": ["filling"]}
      ]
   },
   {
     "apikey":      "110990",
     "cbroker":     "http://orion:1026",
     "entity_type": "Device",
     "resource":    "/iot/d",
     "protocol":    "PDI-IoTA-UltraLight",
     "transport":   "HTTP",
     "timezone":    "Europe/Berlin",
     "attributes": [
        {"object_id": "bpm","type": "Integer","name": "heartRate",
        "metadata": {"unitCode": {"type": "Text","value": "5K"}}
        },
        {"object_id": "d", "name": "statusDescription", "type": "Property"},
        {"object_id": "s", "name": "status", "type": "Integer"},
        {"object_id": "gps", "name": "location", "type": "geo:point"}
      ],
      "static_attributes": [
        {"name": "description", "type":"Property", "value": "Animal Collar"},
        {"name": "category", "type":"Property", "value": ["sensor"]},
        {"name": "controlledProperty", "type": "Property", "value": ["heartRate", "location", "status"]},
        {"name": "supportedProtocol", "type": "Property", "value": ["ul20"]}
      ]
   },
   {
     "apikey":      "98699",
     "cbroker":     "http://orion:1026",
     "entity_type": "Device",
     "resource":    "/iot/d",
     "protocol":    "PDI-IoTA-UltraLight",
     "transport":   "HTTP",
     "timezone":    "Europe/Berlin",
     "attributes": [
        {"object_id": "bpm","type": "Integer","name": "heartRate",
        "metadata": {"unitCode": {"type": "Text","value": "5K"}}
        },
        {"object_id": "s", "name": "status", "type": "Integer"},
        {"object_id": "d", "name": "statusDescription", "type": "Property"},
        {"object_id": "gps", "name": "location", "type": "geo:point"}
      ],
      "static_attributes": [
        {"name": "description", "type":"Property", "value": "Animal Collar"},
        {"name": "category", "type":"Property", "value": ["sensor"]},
        {"name": "controlledProperty", "type": "Property", "value": ["heartRate", "location", "status"]},
        {"name": "function", "type": "Property", "value":["sensing"]},
        {"name": "supportedProtocol", "type": "Property", "value": ["ul20"]}
      ]
   },
   {
     "apikey":      "112903447",
     "cbroker":     "http://orion:1026",
     "entity_type": "Water",
     "resource":    "/iot/d",
     "protocol":    "PDI-IoTA-UltraLight",
     "transport":   "HTTP",
     "timezone":    "Europe/Berlin",
     "commands": [
        {"name": "on", "type": "command"},
        {"name": "off", "type": "command"}
      ],
      "static_attributes": [
        {"name": "description", "type":"Property", "value": "Irrigation System"},
        {"name": "category", "type":"Property", "value": ["actuator"]},
        {"name": "supportedProtocol", "type": "Property", "value": ["ul20"]}
      ]
   },
   {
     "apikey":      "1067386313",
     "cbroker":     "http://orion:1026",
     "entity_type": "Tractor",
     "resource":    "/iot/d",
     "protocol":    "PDI-IoTA-UltraLight",
     "transport":   "HTTP",
     "timezone":    "Europe/Berlin",
     "attributes": [
        {"object_id": "s", "name": "status", "type": "Integer"},
        {"object_id": "d", "name": "statusDescription", "type": "Property"},
        {"object_id": "gps", "name": "location", "type": "geo:point"}
      ],
     "commands": [
        {"name": "start", "type": "command"},
        {"name": "stop", "type": "command"}
      ],
      "static_attributes": [
        {"name": "description", "type":"Property", "value": "Tractor FMIS"},
        {"name": "category", "type":"Property", "value": ["actuator", "sensor"]},
        {"name": "controlledProperty", "type": "Property", "value": ["location", "status"]},
        {"name": "supportedProtocol", "type": "Property", "value": ["ul20"]}
      ]
   }

 ]
}'

####################################################
#
# Provision actuators for Farm 001
#

curl -s -o /dev/null -X POST \
  'http://iot-agent:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "temperature001",
     "entity_name": "urn:ngsi-ld:Device:temperature001",
     "entity_type": "TemperatureSensor",
     "static_attributes": [
         {"name": "controllingAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:farm001"}
     ]
   },
   {
      "device_id": "water001",
      "entity_name": "urn:ngsi-ld:Device:water001",
      "entity_type": "Water",
      "endpoint": "http://context-provider:3001/iot/water001",
      "static_attributes": [
        {"name": "controllingAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:farm001"}
      ]
    },
    {
      "device_id": "filling001",
      "entity_name": "urn:ngsi-ld:Device:filling001",
      "entity_type": "FillingSensor",
      "endpoint": "http://context-provider:3001/iot/filling001",
      "static_attributes": [
        {"name": "controllingAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:farm001"},
        {"name": "location", "type": "GeoProperty", "value": [13.3505, 52.5144]}
      ]
    }, 
    {
      "device_id": "tractor001",
      "entity_name": "urn:ngsi-ld:Device:tractor001",
      "entity_type": "Tractor",
      "endpoint": "http://context-provider:3001/iot/tractor001",
      "static_attributes": [
          {"name": "controllingAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:farm001"}
      ]
    }
  ]
}
'

####################################################
#
# Provision actuators for Farm 002
#

curl -s -o /dev/null -X POST \
  'http://iot-agent:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "temperature002",
     "entity_name": "urn:ngsi-ld:Device:temperature002",
     "entity_type": "TemperatureSensor",
     "static_attributes": [
         {"name": "controllingAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:barn002"}
     ]
   },
   {
      "device_id": "water002",
      "entity_name": "urn:ngsi-ld:Device:water002",
      "entity_type": "Water",
      "endpoint": "http://context-provider:3001/iot/water002",
      "static_attributes": [
        {"name": "controllingAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:barn002"}
      ]
    },
    {
      "device_id": "filling002",
      "entity_name": "urn:ngsi-ld:Device:filling002",
      "entity_type": "FillingSensor",
      "endpoint": "http://context-provider:3001/iot/filling002",
      "static_attributes": [
        {"name": "controllingAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:barn002"},
        {"name": "location", "type": "GeoProperty", "value": [13.3698, 52.5163]}
      ]
    }, 
    {
      "device_id": "tractor002",
      "entity_name": "urn:ngsi-ld:Device:tractor002",
      "entity_type": "Tractor",
      "endpoint": "http://context-provider:3001/iot/tractor002",
      "static_attributes": [
          {"name": "controllingAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:barn002"}
      ]
    }
  ]
}
'

####################################################
#
# Provision actuators for Farm 003
#

curl -s -o /dev/null -X POST \
  'http://iot-agent:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "temperature003",
     "entity_name": "urn:ngsi-ld:Device:temperature003",
     "entity_type": "TemperatureSensor",
     "static_attributes": [
         {"name": "controllingAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:tower003"}
     ]
   },
   {
      "device_id": "water003",
      "entity_name": "urn:ngsi-ld:Device:water003",
      "entity_type": "Water",
      "endpoint": "http://context-provider:3001/iot/water003",
      "static_attributes": [
        {"name": "controllingAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:tower003"}
      ]
    },
    {
      "device_id": "filling003",
      "entity_name": "urn:ngsi-ld:Device:filling003",
      "entity_type": "FillingSensor",
      "endpoint": "http://context-provider:3001/iot/filling003",
      "static_attributes": [
        {"name": "controllingAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:tower003"},
        {"name": "location", "type": "GeoProperty", "value": [13.3598, 52.5165]}
      ]
    }, 
    {
      "device_id": "tractor003",
      "entity_name": "urn:ngsi-ld:Device:tractor003",
      "entity_type": "Tractor",
      "endpoint": "http://context-provider:3001/iot/tractor003",
      "static_attributes": [
          {"name": "controllingAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:tower003"}
      ]
    }
  ]
}
'

####################################################
#
# Provision actuators for Farm 004
#

curl -s -o /dev/null -X POST \
  'http://iot-agent:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "temperature004",
     "entity_name": "urn:ngsi-ld:Device:temperature004",
     "entity_type": "TemperatureSensor",
     "static_attributes": [
         {"name": "controllingAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:farm002"}
     ]
   },
   {
      "device_id": "water004",
      "entity_name": "urn:ngsi-ld:Device:water004",
      "entity_type": "Water",
      "endpoint": "http://context-provider:3001/iot/water004",
      "static_attributes": [
        {"name": "controllingAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:farm002"}
      ]
    },
    {
      "device_id": "filling004",
      "entity_name": "urn:ngsi-ld:Device:filling004",
      "entity_type": "FillingSensor",
      "endpoint": "http://context-provider:3001/iot/filling004",
      "static_attributes": [
        {"name": "controllingAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:farm002"},
        {"name": "location", "type": "GeoProperty", "value": [13.3127, 52.4893]}
      ]
    }, 
    {
      "device_id": "tractor004",
      "entity_name": "urn:ngsi-ld:Device:tractor004",
      "entity_type": "Tractor",
      "endpoint": "http://context-provider:3001/iot/tractor004",
      "static_attributes": [
          {"name": "controllingAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:farm002"}
      ]
    }
  ]
}
'
echo -e " \033[1;32mdone\033[0m"